version: '3.8'

networks:
  proxy:
    external: true

services:
  whoami:
    image: traefik/whoami:latest
    container_name: simple-service
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Path(`/whoami`)"
